# Change these first
owner: Edinburgh-College-of-Art # Your GitHub organization or username, where this repository lives
repo: DI-upptime # The name of this repository

sites:
  - name: Design Informatics
    url: https://designinformatics.org
  - name: Ripple Framework
    url: https://ripple.designinformatics.org
  - name: FIRE App
    url: https://fire-app.designinformatics.org
  - name: A Token Gesture
    url: https://nft.inspace.ed.ac.uk
  - name: A Token Gesture (DI)
    url: https://nft.designinformatics.org
  - name: GeoCoin
    url: https://geocoin.site
  - name: Ticket Designer
    url: https://ticket-designer.designinformatics.org
  - name: Data Laundering
    url: https://data-laundering.designinformatics.org
  - name: VizBlocks Website
    url: https://vizblocks.creativeinformatics.org
  - name: Flow Ctrl
    url: https://flow.creativeinformatics.org
  - name: VisTools
    url: https://vistools.net
  - name: TNRO
    url: https://observatory.newreal.cc
  - name: AWEN Website
    url: https://www.awen.earth
  - name: AWEN App
    url: https://walk.awen.earth
  - name: TRoll
    url: https://toiletroll.chrisspeed.net
  - name: SHAW-dev
    url: https://shaw-dev.designinformatics.org
  - name: SHAW-prod
    url: https://shaw.designinformatics.org
  

status-website:
  cname: uptime.designinformatics.org
  logoUrl: https://www.designinformatics.org/wp-content/themes/design-info/resources/assets/images/di_logo.png
  name: Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
